/**
 * phase2s conduct — conductor command handler.
 *
 * Collapses the manual spec-writing step:
 *   phase2s conduct "<goal>" → generates spec → runs orchestrator
 *
 * The spec is generated by conductorGenSpec() (conductor-prompt.ts),
 * validated by lintSpec(), and saved to .phase2s/specs/ before being
 * handed off to the existing runGoal() executor with --orchestrator.
 *
 * Sprint 90 additions:
 *   - conduct-log.jsonl: every run appended via appendConductLog() in finally
 *   - --validate flag: 4 inline structural checks before DAG preview
 *   - Spec refinement loop: tri-mode prompt allows feedback → regen (max 3 rounds)
 */

import { createHash } from "node:crypto";
import { createInterface } from "node:readline";
import chalk from "chalk";
import { loadConfig } from "../core/config.js";
import { parseSpec } from "../core/spec-parser.js";
import { buildDependencyGraph, formatExecutionLevels } from "../goal/dependency-graph.js";
import { runGoal } from "./goal.js";
import { conductorGenSpec, CONDUCTOR_MIN_SUBTASKS, CONDUCTOR_MAX_SUBTASKS } from "./conductor-prompt.js";
import { isKnownModelPrefix } from "./provider-registry.js";
import { renderConductSummary } from "./conduct-summary.js";
import { lintSpec } from "./lint.js";
import { appendConductLog } from "./conduct-log.js";
import type { GoalResult } from "./goal.js";

/** Maximum refinement rounds before falling back to a binary run/exit prompt. */
const MAX_REFINEMENT_ROUNDS = 3;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ConductOptions {
  /** Generate spec and print DAG preview, do not run the orchestrator. */
  dryRun?: boolean;
  /** Override model for spec generation (default: config.smart_model). */
  model?: string;
  /** Max parallel workers per level (passed to orchestrator). */
  workers?: number;
  /** Max retry loops (passed to orchestrator, coerced to string). */
  maxAttempts?: number;
  /** Suppress verbose status output from conductor and goal executor. */
  quiet?: boolean;
  /** Write final goal summary to this path as JSON. */
  output?: string;
  /** Skip the "▶ Run? [y/N]" confirmation even in TTY mode (D6). */
  yes?: boolean;
  /** Run adversarial review before execution; halt on CHALLENGED verdict. */
  reviewBeforeRun?: boolean;
  /** Enable tmux dashboard for visual progress during parallel execution. */
  dashboard?: boolean;
  /** Resume from a prior failed run using the checkpoint state file. */
  resume?: boolean;
  /** Run 4 inline structural validation checks before DAG preview (Sprint 90). */
  validate?: boolean;
}

// ---------------------------------------------------------------------------
// runConduct
// ---------------------------------------------------------------------------

/**
 * Execute the conductor: generate a role-annotated spec from a natural-language
 * goal, preview the DAG, optionally confirm, then run the orchestrator.
 *
 * @param goal    Natural-language goal string.
 * @param options Conductor options (dry-run, model, workers, etc.).
 * @param cwd     Working directory (passed to GoalOptions so runGoal resolves
 *                spec paths relative to the invocation directory, not install).
 */
export async function runConduct(
  goal: string,
  options: ConductOptions,
  cwd: string,
): Promise<void> {
  const startMs = Date.now();
  const config = await loadConfig();

  // --- B: Warn on unrecognized --model values (best-effort heuristic, not a hard block) ---
  if (options.model && !options.quiet) {
    const m = options.model.toLowerCase();
    const isOllamaProvider = config.provider === "ollama";
    const hasColonFormat = m.includes(":");
    const isTierAlias = m === "fast" || m === "smart";
    if (!isOllamaProvider && !hasColonFormat && !isTierAlias && !isKnownModelPrefix(m)) {
      console.warn(
        chalk.yellow(
          `⚠ Unrecognized model "${options.model}" — passing through. ` +
          `Check your provider docs if the LLM call fails.`,
        ),
      );
    }
  }

  if (!options.quiet) {
    console.log(chalk.cyan("📋 Generating spec from goal..."));
  }

  // Declare result variables before try so the finally block can read them.
  let result: GoalResult | undefined;
  let success = false;
  let currentSpecPath = "";
  let currentSpecContent = "";
  let currentSpecHash = "";
  let rounds = 0;

  try {
    // --- Initial spec generation ---
    const genResult = await conductorGenSpec(goal, config, {
      model: options.model,
      cwd,
      quiet: options.quiet,
      _skipModelWarn: true, // runConduct already validated above
    });

    currentSpecPath = genResult.specPath;
    currentSpecContent = genResult.specContent;

    if (!currentSpecPath) {
      console.error(chalk.red("✗ Spec generation failed. The LLM may have timed out or produced an invalid spec."));
      process.exitCode = 1;
      return;
    }

    // Compute spec hash (first 8 hex chars of sha256).
    currentSpecHash = createHash("sha256").update(currentSpecContent).digest("hex").slice(0, 8);

    // --- Refinement loop (max MAX_REFINEMENT_ROUNDS) ---
    while (true) {
      const spec = parseSpec(currentSpecContent);

      // Part 3: --validate flag — 4 inline structural checks
      if (options.validate && options.dryRun && !options.quiet) {
        console.warn(chalk.yellow("  ⚠ --validate is skipped in --dry-run mode."));
      }
      if (options.validate && !options.dryRun) {
        const shouldContinue = await runValidate(spec, options);
        if (!shouldContinue) return;
      }

      // Show DAG preview
      const dagResult = spec.decomposition.length >= 2
        ? buildDependencyGraph(spec.decomposition)
        : null;

      if (!options.quiet) {
        if (dagResult) {
          console.log("\n" + formatExecutionLevels(dagResult, spec.decomposition));
        } else if (spec.decomposition.length > 0) {
          console.log(chalk.dim(`\n  ${spec.decomposition.length} subtask(s) — no dependency graph (need 2+)`));
        }
        console.log(chalk.dim(`  Spec saved: ${currentSpecPath}`));
      }

      if (options.dryRun) return;

      // --- Part 4: Tri-mode confirmation / refinement loop ---
      if (process.stdin.isTTY && !options.yes) {
        if (rounds >= MAX_REFINEMENT_ROUNDS) {
          // Max rounds reached — fall back to binary prompt (no further refinement).
          if (!options.quiet) {
            console.log(chalk.yellow(`  Maximum refinement rounds (${MAX_REFINEMENT_ROUNDS}) reached.`));
          }
          const confirmed = await prompt("▶ Run with current spec? [y/N] ");
          if (!confirmed) return;
          break; // proceed to execution
        }

        const triResult = await promptTriMode("▶ Run? [y/N] or describe changes to refine spec: ");
        if (triResult === "run") {
          break; // proceed to execution
        }
        if (triResult === "exit") {
          return; // user declined
        }

        // User provided feedback — regenerate spec.
        const feedback = triResult;
        rounds++;
        if (!options.quiet) {
          console.log(chalk.cyan(`\n🔄 Refining spec (round ${rounds}/${MAX_REFINEMENT_ROUNDS})...`));
        }

        const refined = await conductorGenSpec(goal, config, {
          model: options.model,
          cwd,
          quiet: options.quiet,
          _skipModelWarn: true,
          feedback,
          _prevSpecContent: currentSpecContent,
        });

        if (!refined.specPath) {
          console.error(chalk.red("✗ Spec refinement failed. Proceeding with previous spec."));
          rounds--; // don't count the failed round
          break;
        }

        currentSpecPath = refined.specPath;
        currentSpecContent = refined.specContent;
        currentSpecHash = createHash("sha256").update(currentSpecContent).digest("hex").slice(0, 8);
        continue; // show updated DAG and re-prompt
      } else {
        // Non-TTY or --yes: proceed directly.
        break;
      }
    }

    // --- Execute ---
    result = await runGoal(currentSpecPath, {
      maxAttempts: String(options.maxAttempts ?? 3),
      orchestrator: true,
      workers: options.workers,
      quiet: options.quiet,
      cwd,
      reviewBeforeRun: options.reviewBeforeRun,
      dashboard: options.dashboard,
      resume: options.resume,
    });

    success = result.success;

    // Render structured post-run summary (gated on !quiet inside renderConductSummary)
    renderConductSummary(result, currentSpecPath, goal, { quiet: options.quiet });

    if (options.output) {
      try {
        const { writeFile } = await import("node:fs/promises");
        await writeFile(options.output, JSON.stringify(result, null, 2), "utf8");
        if (!options.quiet) {
          console.log(chalk.dim(`  Summary written to: ${options.output}`));
        }
      } catch (err) {
        console.error(chalk.red(`✗ Failed to write output file: ${options.output} — ${(err as Error).message}`));
      }
    }

    process.exitCode = result.success ? 0 : 1;
  } finally {
    // Part 1: Append conduct log entry when spec generation was attempted.
    // Guard on currentSpecPath so we don't log entries from config-load failures
    // that exit before conductorGenSpec() is ever called.
    // Wrapped in try/catch so log write failures never mask the real exit code.
    if (currentSpecPath) {
      try {
        const spec = currentSpecContent ? parseSpec(currentSpecContent) : null;
        await appendConductLog(
          {
            ts: new Date().toISOString(),
            goal: goal.slice(0, 200),
            specPath: currentSpecPath,
            specHash: currentSpecHash,
            subtaskCount: spec?.decomposition.length ?? 0,
            roles: spec
              ? [...new Set(spec.decomposition.flatMap((s) => (s.role ? [s.role] : [])))]
              : [],
            success,
            durationMs: Date.now() - startMs,
            runLogPath: result?.runLogPath ?? "",
            rounds,
          },
          cwd,
        );
      } catch (err) {
        console.warn(`[conduct-log] Failed to write log entry: ${(err as Error).message}`);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// runValidate — Part 3: inline structural validation (--validate flag)
// ---------------------------------------------------------------------------

/**
 * Run the 4 structural validation checks on the parsed spec.
 * Returns true if execution should continue, false if it should abort.
 *
 * Checks:
 *   1. Subtask count ≥ CONDUCTOR_MIN_SUBTASKS
 *   2. Subtask count ≤ CONDUCTOR_MAX_SUBTASKS
 *   3. lintSpec passes (no error-severity issues)
 *   4. No duplicate roles
 *
 * Behavior on failures:
 *   - TTY, not --yes: prompt "Proceed anyway? [y/N]". N → exit 1.
 *   - Non-TTY (pipe or CI): exit 1 immediately.
 *   - --yes: console.warn to stderr, continue.
 */
async function runValidate(
  spec: ReturnType<typeof parseSpec>,
  options: ConductOptions,
): Promise<boolean> {
  const failures: string[] = [];
  let passed = 0;
  const total = 4;

  // Check 1: min subtask count
  if (spec.decomposition.length < CONDUCTOR_MIN_SUBTASKS) {
    failures.push(`subtask count ${spec.decomposition.length} < min ${CONDUCTOR_MIN_SUBTASKS}`);
  } else {
    passed++;
  }

  // Check 2: max subtask count
  if (spec.decomposition.length > CONDUCTOR_MAX_SUBTASKS) {
    failures.push(`subtask count ${spec.decomposition.length} > max ${CONDUCTOR_MAX_SUBTASKS}`);
  } else {
    passed++;
  }

  // Check 3: lintSpec (error-severity issues only)
  const lintResult = lintSpec(spec);
  const lintErrors = lintResult.issues.filter((i) => i.severity === "error");
  if (lintErrors.length > 0) {
    failures.push(`lintSpec: ${lintErrors.map((i) => i.message).join("; ")}`);
  } else {
    passed++;
  }

  // Check 4: no duplicate roles
  const roles = spec.decomposition.flatMap((s) => (s.role ? [s.role] : []));
  const seen = new Set<string>();
  const dupes: string[] = [];
  for (const r of roles) {
    if (seen.has(r)) dupes.push(r);
    seen.add(r);
  }
  if (dupes.length > 0) {
    failures.push(`duplicate roles found: ${[...new Set(dupes)].join(", ")}`);
  } else {
    passed++;
  }

  if (!options.quiet) {
    if (failures.length === 0) {
      console.log(chalk.green(`  Audit: ${passed}/${total} checks passed ✓`));
    } else {
      console.log(chalk.red(`  Audit: ${passed}/${total} checks passed — failures:`));
      for (const f of failures) {
        console.log(chalk.red(`    ${f}`));
      }
    }
  }

  if (failures.length === 0) return true;

  // Failures — decide whether to continue.
  if (options.yes) {
    console.warn(
      `Warning: conduct --validate failed ${failures.length} check(s). Proceeding due to --yes.`,
    );
    return true;
  }

  if (!process.stdin.isTTY) {
    // Non-TTY: strict mode, exit 1.
    process.exitCode = 1;
    return false;
  }

  // TTY: ask the user.
  const proceed = await prompt("  Validation failed. Proceed anyway? [y/N] ");
  if (!proceed) {
    process.exitCode = 1;
    return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Tri-mode prompt for spec confirmation / refinement (Part 4, Sprint 90).
 *
 * Returns:
 *   'run'   — user typed y or yes
 *   'exit'  — user typed nothing, n, or no
 *   string  — any other input (treated as refinement feedback)
 */
export async function promptTriMode(question: string): Promise<"run" | "exit" | string> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      if (a === "y" || a === "yes") {
        resolve("run");
      } else if (a === "" || a === "n" || a === "no") {
        resolve("exit");
      } else {
        // Return the raw (untrimmed/unlowercased) feedback for the LLM.
        resolve(answer.trim());
      }
    });
  });
}

/** Binary y/N prompt — returns true for y/yes, false otherwise. */
async function prompt(question: string): Promise<boolean> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      resolve(a === "y" || a === "yes");
    });
  });
}
