/**
 * phase2s conduct — conductor command handler.
 *
 * Collapses the manual spec-writing step:
 *   phase2s conduct "<goal>" → generates spec → runs orchestrator
 *
 * The spec is generated by conductorGenSpec() (conductor-prompt.ts),
 * validated by lintSpec(), and saved to .phase2s/specs/ before being
 * handed off to the existing runGoal() executor with --orchestrator.
 */

import { createInterface } from "node:readline";
import chalk from "chalk";
import { loadConfig } from "../core/config.js";
import { parseSpec } from "../core/spec-parser.js";
import { buildDependencyGraph, formatExecutionLevels } from "../goal/dependency-graph.js";
import { runGoal } from "./goal.js";
import { conductorGenSpec } from "./conductor-prompt.js";
import { isKnownModelPrefix } from "./provider-registry.js";
import { renderConductSummary } from "./conduct-summary.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ConductOptions {
  /** Generate spec and print DAG preview, do not run the orchestrator. */
  dryRun?: boolean;
  /** Override model for spec generation (default: config.smart_model). */
  model?: string;
  /** Max parallel workers per level (passed to orchestrator). */
  workers?: number;
  /** Max retry loops (passed to orchestrator, coerced to string). */
  maxAttempts?: number;
  /** Suppress verbose status output from conductor and goal executor. */
  quiet?: boolean;
  /** Write final goal summary to this path as JSON. */
  output?: string;
  /** Skip the "▶ Run? [y/N]" confirmation even in TTY mode (D6). */
  yes?: boolean;
  /** Run adversarial review before execution; halt on CHALLENGED verdict. */
  reviewBeforeRun?: boolean;
  /** Enable tmux dashboard for visual progress during parallel execution. */
  dashboard?: boolean;
  /** Resume from a prior failed run using the checkpoint state file. */
  resume?: boolean;
}

// ---------------------------------------------------------------------------
// runConduct
// ---------------------------------------------------------------------------

/**
 * Execute the conductor: generate a role-annotated spec from a natural-language
 * goal, preview the DAG, optionally confirm, then run the orchestrator.
 *
 * @param goal    Natural-language goal string.
 * @param options Conductor options (dry-run, model, workers, etc.).
 * @param cwd     Working directory (passed to GoalOptions so runGoal resolves
 *                spec paths relative to the invocation directory, not install).
 */
export async function runConduct(
  goal: string,
  options: ConductOptions,
  cwd: string,
): Promise<void> {
  const config = await loadConfig();

  // --- B: Warn on unrecognized --model values (best-effort heuristic, not a hard block) ---
  // Skip validation for Ollama (models use "name:tag" format which doesn't match any prefix),
  // or when the model string itself contains ":" (Ollama tag format used with other providers),
  // or when the model is a tier alias ("fast"/"smart" resolved inside conductorGenSpec),
  // or when the model starts with a known provider prefix.
  // Gated on !options.quiet so --quiet suppresses this warning.
  if (options.model && !options.quiet) {
    const m = options.model.toLowerCase();
    const isOllamaProvider = config.provider === "ollama";
    const hasColonFormat = m.includes(":"); // e.g. "gemma4:latest", "qwen2.5-coder:7b"
    const isTierAlias = m === "fast" || m === "smart"; // resolved in conductorGenSpec (D5)
    if (!isOllamaProvider && !hasColonFormat && !isTierAlias && !isKnownModelPrefix(m)) {
      console.warn(
        chalk.yellow(
          `⚠ Unrecognized model "${options.model}" — passing through. ` +
          `Check your provider docs if the LLM call fails.`,
        ),
      );
    }
  }

  if (!options.quiet) {
    console.log(chalk.cyan("📋 Generating spec from goal..."));
  }

  const { specPath, specContent } = await conductorGenSpec(goal, config, {
    model: options.model,
    cwd,
    quiet: options.quiet,
    _skipModelWarn: true, // runConduct already validated above — avoid double-warn
  });

  if (!specPath) {
    console.error(chalk.red("✗ Spec generation failed. The LLM may have timed out or produced an invalid spec."));
    process.exitCode = 1;
    return;
  }

  // Show DAG preview
  const spec = parseSpec(specContent);
  const dagResult = spec.decomposition.length >= 2
    ? buildDependencyGraph(spec.decomposition)
    : null;

  if (!options.quiet) {
    if (dagResult) {
      console.log("\n" + formatExecutionLevels(dagResult, spec.decomposition));
    } else if (spec.decomposition.length > 0) {
      console.log(chalk.dim(`\n  ${spec.decomposition.length} subtask(s) — no dependency graph (need 2+)`));
    }
    console.log(chalk.dim(`  Spec saved: ${specPath}`));
  }

  if (options.dryRun) return;

  // Interactive confirmation — skip in non-TTY or when --yes is set (D6)
  if (process.stdin.isTTY && !options.yes) {
    const confirmed = await prompt("▶ Run? [y/N] ");
    if (!confirmed) return;
  }

  // Delegate to the existing goal executor with orchestrator mode always on.
  // Pass the three new parity flags through to GoalOptions.
  const result = await runGoal(specPath, {
    maxAttempts: String(options.maxAttempts ?? 3), // D3: coerce to string
    orchestrator: true,
    workers: options.workers,
    quiet: options.quiet,       // D2: quiet flag now on GoalOptions
    cwd,                        // D1: cwd now on GoalOptions
    reviewBeforeRun: options.reviewBeforeRun,
    dashboard: options.dashboard,
    resume: options.resume,
  });

  // Render structured post-run summary (gated on !quiet inside renderConductSummary)
  renderConductSummary(result, specPath, goal, { quiet: options.quiet });

  if (options.output) {
    try {
      const { writeFile } = await import("node:fs/promises");
      await writeFile(options.output, JSON.stringify(result, null, 2), "utf8");
      if (!options.quiet) {
        console.log(chalk.dim(`  Summary written to: ${options.output}`));
      }
    } catch (err) {
      console.error(chalk.red(`✗ Failed to write output file: ${options.output} — ${(err as Error).message}`));
    }
  }

  process.exitCode = result.success ? 0 : 1;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function prompt(question: string): Promise<boolean> {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      const a = answer.trim().toLowerCase();
      resolve(a === "y" || a === "yes");
    });
  });
}
