/**
 * phase2s init — interactive setup wizard.
 *
 * Asks up to 4 questions, writes .phase2s.yaml, validates prerequisites,
 * and prints next steps. Designed to run once after install.
 *
 * Pure functions (formatConfig, checkPrerequisites) are exported for testing.
 * The interactive prompt loop is in promptConfig (not exported).
 */

import { createInterface } from "node:readline";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import chalk from "chalk";
import { parse as parseYaml } from "yaml";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Provider = "codex-cli" | "openai-api" | "anthropic" | "ollama" | "openrouter" | "gemini" | "minimax";

export interface InitConfig {
  provider: Provider;
  /** API key (OpenAI or Anthropic). Not written to config for codex-cli/ollama. */
  apiKey?: string;
  /** fast_model tier — optional. */
  fastModel?: string;
  /** smart_model tier — optional. */
  smartModel?: string;
  /** OpenRouter API key. Not written for other providers. */
  openrouterApiKey?: string;
  /** Gemini API key. Not written for other providers. */
  geminiApiKey?: string;
  /** MiniMax API key. Not written for other providers. */
  minimaxApiKey?: string;
  /** Slack incoming webhook URL — optional. */
  slackWebhook?: string;
  /** Discord incoming webhook URL — optional. */
  discordWebhook?: string;
  /** Microsoft Teams incoming webhook URL — optional. */
  teamsWebhook?: string;
  /** Telegram bot token (from BotFather). */
  telegramToken?: string;
  /** Telegram chat ID to send to. */
  telegramChatId?: string;
}

export interface PrereqResult {
  ok: boolean;
  warnings: string[];
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Format an InitConfig as a .phase2s.yaml string.
 * Produces a commented file so users can easily extend it.
 */
export function formatConfig(config: InitConfig): string {
  const lines: string[] = [
    "# Phase2S configuration — generated by phase2s init",
    "# Docs: https://github.com/scanton/phase-2-s/blob/main/docs/configuration.md",
    "",
    `provider: ${config.provider}`,
  ];

  if (config.provider === "openai-api" && config.apiKey) {
    lines.push(`apiKey: "${config.apiKey}"`);
    lines.push("");
    lines.push("# Consider using OPENAI_API_KEY env var instead of storing keys in config.");
  }

  if (config.provider === "anthropic" && config.apiKey) {
    lines.push(`anthropicApiKey: "${config.apiKey}"`);
    lines.push("");
    lines.push("# Consider using ANTHROPIC_API_KEY env var instead of storing keys in config.");
  }

  if (config.provider === "openrouter" && config.openrouterApiKey) {
    lines.push(`openrouterApiKey: "${config.openrouterApiKey}"`);
    lines.push("");
    lines.push("# Consider using OPENROUTER_API_KEY env var instead of storing keys in config.");
    lines.push("# Model names use provider-prefixed slugs: openai/gpt-4o, anthropic/claude-3-5-sonnet,");
    lines.push("# google/gemini-pro-1.5, meta-llama/llama-3.1-8b-instruct");
    lines.push("# Browse all models at https://openrouter.ai/models");
  }

  if (config.provider === "gemini" && config.geminiApiKey) {
    lines.push(`geminiApiKey: "${config.geminiApiKey}"`);
    lines.push("");
    lines.push("# Consider using GEMINI_API_KEY env var instead of storing keys in config.");
    lines.push("# Get a free key at https://aistudio.google.com/apikey — keys start with 'AIza'.");
    lines.push("# Default model: gemini-2.0-flash. Upgrade with: model: gemini-2.5-pro");
  }

  if (config.provider === "minimax" && config.minimaxApiKey) {
    lines.push(`minimaxApiKey: "${config.minimaxApiKey}"`);
    lines.push("");
    lines.push("# Consider using MINIMAX_API_KEY env var instead of storing keys in config.");
    lines.push("# Get a key at https://platform.minimax.io/");
    lines.push("# Default model: MiniMax-M2.5. Upgrade with: model: MiniMax-M2.7");
  }

  const hasTiers = config.fastModel || config.smartModel;
  if (hasTiers) {
    lines.push("");
    lines.push("# Model tier routing");
    lines.push("# Skills declare 'model: fast' or 'model: smart' in their SKILL.md frontmatter.");
    if (config.fastModel) lines.push(`fast_model: ${config.fastModel}`);
    if (config.smartModel) lines.push(`smart_model: ${config.smartModel}`);
  }

  const hasNotify = config.slackWebhook || config.discordWebhook || config.teamsWebhook || (config.telegramToken && config.telegramChatId);
  if (hasNotify) {
    lines.push("");
    lines.push("# Notifications — sent after dark factory runs (phase2s goal --notify)");
    lines.push("notify:");
    if (config.slackWebhook) lines.push(`  slack: "${config.slackWebhook}"`);
    if (config.discordWebhook) lines.push(`  discord: "${config.discordWebhook}"`);
    if (config.teamsWebhook) lines.push(`  teams: "${config.teamsWebhook}"`);
    if (config.telegramToken && config.telegramChatId) {
      lines.push("  telegram:");
      lines.push(`    token: "${config.telegramToken}"`);
      lines.push(`    chatId: "${config.telegramChatId}"`);
    }
    lines.push("  # mac: true  # uncomment to enable macOS system notifications too");
  }

  return lines.join("\n") + "\n";
}

/**
 * Check that the prerequisites for the chosen provider are available.
 * Returns a list of warnings (not errors — users can fix post-init).
 * Never throws.
 */
export function checkPrerequisites(config: InitConfig): PrereqResult {
  const warnings: string[] = [];

  switch (config.provider) {
    case "codex-cli": {
      const result = spawnSync("codex", ["--version"], { stdio: "pipe" });
      if (result.error) {
        warnings.push(
          "codex CLI not found in PATH. Install with: npm install -g @openai/codex",
        );
      }
      break;
    }
    case "openai-api": {
      if (config.apiKey && !config.apiKey.startsWith("sk-")) {
        warnings.push("OpenAI API key should start with 'sk-'. Double-check your key.");
      }
      if (!config.apiKey && !process.env.OPENAI_API_KEY) {
        warnings.push(
          "No API key provided. Set OPENAI_API_KEY or re-run phase2s init.",
        );
      }
      break;
    }
    case "anthropic": {
      if (config.apiKey && !config.apiKey.startsWith("sk-ant-")) {
        warnings.push("Anthropic API key should start with 'sk-ant-'. Double-check your key.");
      }
      if (!config.apiKey && !process.env.ANTHROPIC_API_KEY) {
        warnings.push(
          "No API key provided. Set ANTHROPIC_API_KEY or re-run phase2s init.",
        );
      }
      break;
    }
    case "ollama": {
      const result = spawnSync("ollama", ["list"], { stdio: "pipe" });
      if (result.error) {
        warnings.push(
          "ollama not found in PATH. Install from https://ollama.com and start with: ollama serve",
        );
      }
      break;
    }
    case "openrouter": {
      if (config.openrouterApiKey && !config.openrouterApiKey.startsWith("sk-or-")) {
        warnings.push("OpenRouter API key should start with 'sk-or-'. Double-check your key.");
      }
      if (!config.openrouterApiKey && !process.env.OPENROUTER_API_KEY) {
        warnings.push(
          "No API key provided. Set OPENROUTER_API_KEY or re-run phase2s init.",
        );
      }
      break;
    }
    case "gemini": {
      if (config.geminiApiKey && !config.geminiApiKey.startsWith("AIza")) {
        warnings.push("Gemini API key should start with 'AIza'. Double-check your key at https://aistudio.google.com/apikey");
      }
      if (!config.geminiApiKey && !process.env.GEMINI_API_KEY) {
        warnings.push(
          "No API key provided. Set GEMINI_API_KEY or re-run phase2s init. Get a free key at https://aistudio.google.com/apikey",
        );
      }
      break;
    }
    case "minimax": {
      if (!config.minimaxApiKey && !process.env.MINIMAX_API_KEY) {
        warnings.push(
          "No API key provided. Set MINIMAX_API_KEY or re-run phase2s init. Get a key at https://platform.minimax.io/",
        );
      }
      break;
    }
  }

  return { ok: warnings.length === 0, warnings };
}

/**
 * Read an existing .phase2s.yaml and extract values to pre-fill prompts.
 * Returns an empty object if the file doesn't exist or can't be parsed.
 */
export function readExistingConfig(configPath: string): Record<string, unknown> {
  try {
    const raw = readFileSync(configPath, "utf8");
    const parsed = parseYaml(raw);
    return (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed))
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

// ---------------------------------------------------------------------------
// runInit — entry point
// ---------------------------------------------------------------------------

export interface InitOptions {
  /** Skip interactive prompts. Uses provider from flags or codex-cli default. */
  nonInteractive?: boolean;
  /** Provider override for non-interactive mode. */
  provider?: string;
  /** API key override for non-interactive mode. */
  apiKey?: string;
  /** Fast model override. */
  fastModel?: string;
  /** Smart model override. */
  smartModel?: string;
  /** OpenRouter API key override. */
  openrouterApiKey?: string;
  /** Gemini API key override. */
  geminiApiKey?: string;
  /** MiniMax API key override. */
  minimaxApiKey?: string;
  /** Slack webhook override. */
  slackWebhook?: string;
  /** Discord webhook override. */
  discordWebhook?: string;
  /** Microsoft Teams webhook override. */
  teamsWebhook?: string;
  /** Run the interactive Telegram bot setup wizard instead of normal init. */
  telegramSetup?: boolean;
}

export async function runInit(options: InitOptions = {}): Promise<void> {
  if (options.telegramSetup) {
    await runTelegramSetup();
    return;
  }

  const configPath = resolve(".phase2s.yaml");
  const existing = existsSync(configPath);

  if (existing && !options.nonInteractive) {
    console.log(chalk.yellow("  ⚠  A .phase2s.yaml already exists — values will be pre-filled from it.\n"));
  }

  let config: InitConfig;

  if (options.nonInteractive) {
    // Non-interactive: assemble config from flags, validate, write.
    const providerRaw = options.provider ?? "codex-cli";
    const validProviders: Provider[] = ["codex-cli", "openai-api", "anthropic", "ollama", "openrouter", "gemini", "minimax"];
    if (!validProviders.includes(providerRaw as Provider)) {
      throw new Error(`Unknown provider: ${providerRaw}. Valid: ${validProviders.join(", ")}`);
    }
    config = {
      provider: providerRaw as Provider,
      apiKey: options.apiKey,
      openrouterApiKey: options.openrouterApiKey,
      geminiApiKey: options.geminiApiKey,
      minimaxApiKey: options.minimaxApiKey,
      fastModel: options.fastModel,
      smartModel: options.smartModel,
      slackWebhook: options.slackWebhook,
      discordWebhook: options.discordWebhook,
      teamsWebhook: options.teamsWebhook,
    };
  } else {
    const existingConfig = readExistingConfig(configPath);
    config = await promptConfig(existingConfig);
  }

  // Validate prerequisites
  const { warnings } = checkPrerequisites(config);
  for (const warning of warnings) {
    console.warn(chalk.yellow(`\n  ⚠  ${warning}`));
  }

  // Write config
  const yaml = formatConfig(config);
  writeFileSync(configPath, yaml, "utf8");

  console.log(chalk.green(`\n  ✓  Written .phase2s.yaml`));
  console.log("");
  printNextSteps(config.provider);
}

// ---------------------------------------------------------------------------
// Interactive prompt loop
// ---------------------------------------------------------------------------

async function promptConfig(existing: Record<string, unknown>): Promise<InitConfig> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise((resolve) => rl.question(q, (a) => resolve(a.trim())));

  console.log(chalk.bold("  Phase2S setup\n"));

  // --- Provider ---
  console.log("  Provider:");
  console.log("    1  ChatGPT subscription (codex-cli) — recommended, no API key needed");
  console.log("    2  OpenAI API key");
  console.log("    3  Anthropic API key");
  console.log("    4  Local Ollama (no internet required)");
  console.log("    5  OpenRouter (one key — Claude, GPT-4o, Gemini, and 50+ more)");
  console.log("    6  Google Gemini (free tier available — gemini-2.0-flash by default)");
  console.log("    7  MiniMax (MiniMax-M2.5 by default)");
  console.log("");

  const providerToNum: Record<string, string> = {
    "codex-cli": "1", "openai-api": "2", "anthropic": "3", "ollama": "4", "openrouter": "5", "gemini": "6", "minimax": "7",
  };
  const numToProvider: Record<string, Provider> = {
    "1": "codex-cli", "2": "openai-api", "3": "anthropic", "4": "ollama", "5": "openrouter", "6": "gemini", "7": "minimax",
  };
  const defaultNum = providerToNum[String(existing.provider)] ?? "1";

  const providerRaw = await ask(`  Choice [${defaultNum}]: `);
  const providerKey = providerRaw || defaultNum;
  const provider: Provider = numToProvider[providerKey] ?? (Object.keys(numToProvider).includes(providerKey) ? providerKey as Provider : "codex-cli");

  const config: InitConfig = { provider };

  // --- API key (if needed) ---
  if (provider === "openai-api" || provider === "anthropic") {
    const keyField = provider === "anthropic" ? "anthropicApiKey" : "apiKey";
    const currentKey = String(existing[keyField] ?? "");
    const hint = provider === "anthropic" ? "sk-ant-..." : "sk-...";
    const prompt = currentKey
      ? `  API key (current: ${currentKey.slice(0, 10)}...) [enter to keep]: `
      : `  API key (${hint}): `;
    const key = await ask(prompt);
    config.apiKey = key || currentKey || undefined;
  }

  if (provider === "openrouter") {
    const currentKey = String(existing.openrouterApiKey ?? "");
    const prompt = currentKey
      ? `  OpenRouter API key (current: ${currentKey.slice(0, 10)}...) [enter to keep]: `
      : "  OpenRouter API key (sk-or-...): ";
    const key = await ask(prompt);
    config.openrouterApiKey = key || currentKey || undefined;
  }

  if (provider === "gemini") {
    const currentKey = String(existing.geminiApiKey ?? "");
    const prompt = currentKey
      ? `  Gemini API key (current: ${currentKey.slice(0, 10)}...) [enter to keep]: `
      : "  Gemini API key (AIza...) — get a free key at https://aistudio.google.com/apikey: ";
    const key = await ask(prompt);
    config.geminiApiKey = key || currentKey || undefined;
  }

  if (provider === "minimax") {
    const currentKey = String(existing.minimaxApiKey ?? "");
    const prompt = currentKey
      ? `  MiniMax API key (current: ${currentKey.slice(0, 10)}...) [enter to keep]: `
      : "  MiniMax API key — get a key at https://platform.minimax.io/: ";
    const key = await ask(prompt);
    config.minimaxApiKey = key || currentKey || undefined;
  }

  // --- Model tiers (optional) ---
  const existingFast = String(existing.fast_model ?? "");
  const existingSmart = String(existing.smart_model ?? "");
  if (existingFast || existingSmart) {
    config.fastModel = existingFast || undefined;
    config.smartModel = existingSmart || undefined;
    const update = await ask(`  Update model tiers (fast: ${existingFast || "unset"}, smart: ${existingSmart || "unset"})? (y/N): `);
    if (update.toLowerCase().startsWith("y")) {
      const fast = await ask(`  Fast model [${existingFast || "e.g. gpt-4o-mini"}]: `);
      const smart = await ask(`  Smart model [${existingSmart || "e.g. o3"}]: `);
      config.fastModel = fast || existingFast || undefined;
      config.smartModel = smart || existingSmart || undefined;
    }
  } else {
    const configureTiers = await ask("  Configure fast/smart model tiers for cost optimization? (y/N): ");
    if (configureTiers.toLowerCase().startsWith("y")) {
      const fast = await ask("  Fast model (e.g. gpt-4o-mini for quick tasks): ");
      const smart = await ask("  Smart model (e.g. o3 for deep analysis): ");
      config.fastModel = fast || undefined;
      config.smartModel = smart || undefined;
    }
  }

  // --- Notification webhooks (optional) ---
  const existingNotify = (existing.notify as Record<string, unknown> | undefined) ?? {};
  const existingSlack = String(existingNotify.slack ?? "");
  const existingDiscord = String(existingNotify.discord ?? "");
  const existingTeams = String(existingNotify.teams ?? "");

  // Slack
  if (existingSlack) {
    const updateSlack = await ask(
      `  Slack webhook (current: ${existingSlack.slice(0, 35)}...) — update? (y/N): `,
    );
    if (updateSlack.toLowerCase().startsWith("y")) {
      const slack = await ask("  New Slack webhook URL (or 'none' to remove): ");
      config.slackWebhook = slack.toLowerCase() === "none" ? undefined : (slack || existingSlack);
    } else {
      config.slackWebhook = existingSlack;
    }
  } else {
    const slack = await ask(
      "  Slack webhook URL? (optional — press enter to skip): ",
    );
    config.slackWebhook = slack || undefined;
  }

  // Discord
  if (existingDiscord) {
    const updateDiscord = await ask(
      `  Discord webhook (current: ${existingDiscord.slice(0, 35)}...) — update? (y/N): `,
    );
    if (updateDiscord.toLowerCase().startsWith("y")) {
      const discord = await ask("  New Discord webhook URL (or 'none' to remove): ");
      config.discordWebhook = discord.toLowerCase() === "none" ? undefined : (discord || existingDiscord);
    } else {
      config.discordWebhook = existingDiscord;
    }
  } else {
    const discord = await ask(
      "  Discord webhook URL? (optional — press enter to skip): ",
    );
    config.discordWebhook = discord || undefined;
  }

  // Microsoft Teams
  if (existingTeams) {
    const updateTeams = await ask(
      `  Teams webhook (current: ${existingTeams.slice(0, 35)}...) — update? (y/N): `,
    );
    if (updateTeams.toLowerCase().startsWith("y")) {
      const teams = await ask("  New Teams webhook URL (or 'none' to remove): ");
      config.teamsWebhook = teams.toLowerCase() === "none" ? undefined : (teams || existingTeams);
    } else {
      config.teamsWebhook = existingTeams;
    }
  } else {
    const teams = await ask(
      "  Microsoft Teams webhook URL? (optional — press enter to skip): ",
    );
    config.teamsWebhook = teams || undefined;
  }

  rl.close();
  return config;
}

// ---------------------------------------------------------------------------
// Telegram setup wizard
// ---------------------------------------------------------------------------

/** Max number of getUpdates retries when the bot has no messages yet. */
const TELEGRAM_MAX_RETRIES = 3;

/**
 * Interactive wizard to discover a Telegram chat ID.
 *
 * Flow:
 * 1. Prompt for bot token (from BotFather)
 * 2. Call getUpdates — non-200 = invalid token, bail
 * 3. If result array is empty, ask user to message the bot, retry (max 3x)
 * 4. Pick the entry with the highest update_id (most recent)
 * 5. Print chat ID + YAML snippet
 */
export async function runTelegramSetup(): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise((resolve) => rl.question(q, (a) => resolve(a.trim())));

  console.log(chalk.bold("\n  Telegram setup wizard\n"));
  console.log("  This wizard finds your Telegram chat ID so you can receive phase2s notifications.");
  console.log("  You'll need a bot token from @BotFather (https://t.me/BotFather).\n");

  const token = await ask("  Enter your bot token (from BotFather): ");
  rl.close();

  if (!token) {
    console.error(chalk.red("  No token provided. Run phase2s init --telegram-setup to try again."));
    return;
  }

  let chatId: string | undefined;

  for (let attempt = 0; attempt < TELEGRAM_MAX_RETRIES; attempt++) {
    let data: unknown;
    try {
      const resp = await fetch(`https://api.telegram.org/bot${token}/getUpdates`);
      if (!resp.ok) {
        console.error(chalk.red(`\n  Invalid token — check BotFather (HTTP ${resp.status}).`));
        return;
      }
      data = await resp.json();
    } catch (err) {
      console.error(chalk.red(`\n  Network error: ${err instanceof Error ? err.message : String(err)}`));
      return;
    }

    const result = (data as { result?: unknown[] }).result ?? [];
    if (result.length === 0) {
      if (attempt < TELEGRAM_MAX_RETRIES - 1) {
        console.log(chalk.yellow("\n  No messages received. Send any message to your bot, then press Enter to retry..."));
        await new Promise<void>((res) => {
          const rl2 = createInterface({ input: process.stdin, output: process.stdout });
          rl2.question("", () => { rl2.close(); res(); });
        });
        continue;
      } else {
        console.error(chalk.red("\n  Timed out — message your bot and re-run phase2s init --telegram-setup."));
        return;
      }
    }

    // Pick the entry with the highest update_id (most recent)
    type Update = { update_id: number; message?: { chat?: { id: number } } };
    const sorted = (result as Update[]).sort((a, b) => b.update_id - a.update_id);
    const chatIdNum = sorted[0]?.message?.chat?.id;
    if (chatIdNum === undefined) {
      console.error(chalk.red("\n  Could not parse chat ID from updates. Try sending a text message to your bot."));
      return;
    }
    chatId = String(chatIdNum);
    break;
  }

  if (!chatId) return;

  console.log(chalk.green(`\n  Your chat ID: ${chatId}`));
  console.log("");
  console.log("  Add to .phase2s.yaml:");
  console.log(chalk.cyan("  notify:"));
  console.log(chalk.cyan("    telegram:"));
  console.log(chalk.cyan(`      token: "${token}"`));
  console.log(chalk.cyan(`      chatId: "${chatId}"`));
  console.log("");
  console.log(chalk.dim("  Or set env vars: PHASE2S_TELEGRAM_BOT_TOKEN and PHASE2S_TELEGRAM_CHAT_ID"));
  console.log("");
}

// ---------------------------------------------------------------------------
// Next steps
// ---------------------------------------------------------------------------

function printNextSteps(provider: Provider): void {
  console.log("  Get started:");
  if (provider === "codex-cli") {
    console.log("    1.  Authenticate Codex CLI (one time):  codex auth");
    console.log("    2.  Start the REPL:                     phase2s");
    console.log("    3.  Or run a skill directly:            phase2s run \"/explain src/index.ts\"");
  } else if (provider === "ollama") {
    console.log("    1.  Pull a model (if not done):  ollama pull llama3.1:8b");
    console.log("    2.  Start the REPL:              phase2s");
    console.log("    3.  Or run a skill:              phase2s run \"/explain src/index.ts\"");
  } else if (provider === "openrouter") {
    console.log("    1.  Browse models:               https://openrouter.ai/models");
    console.log("    2.  Set your model in .phase2s.yaml (default: openai/gpt-4o):");
    console.log("        model: anthropic/claude-3-5-sonnet");
    console.log("    3.  Start the REPL:              phase2s");
    console.log("    4.  Or run a skill directly:     phase2s run \"/explain src/index.ts\"");
  } else if (provider === "gemini") {
    console.log("    1.  Verify your API key:         https://aistudio.google.com/apikey");
    console.log("    2.  Default model is gemini-2.0-flash. Upgrade in .phase2s.yaml:");
    console.log("        model: gemini-2.5-pro");
    console.log("    3.  Start the REPL:              phase2s");
    console.log("    4.  Or run a skill directly:     phase2s run \"/explain src/index.ts\"");
  } else if (provider === "minimax") {
    console.log("    1.  Verify your API key:         https://platform.minimax.io/");
    console.log("    2.  Default model is MiniMax-M2.5. Upgrade in .phase2s.yaml:");
    console.log("        model: MiniMax-M2.7");
    console.log("    3.  Start the REPL:              phase2s");
    console.log("    4.  Or run a skill directly:     phase2s run \"/explain src/index.ts\"");
  } else {
    console.log("    1.  Start the REPL:              phase2s");
    console.log("    2.  Or run a skill directly:     phase2s run \"/explain src/index.ts\"");
  }
  console.log("");
  console.log(chalk.dim("  Docs: https://github.com/scanton/phase-2-s/blob/main/docs/getting-started.md"));
  console.log("");
}
