/**
 * phase2s init — interactive setup wizard.
 *
 * Asks up to 4 questions, writes .phase2s.yaml, validates prerequisites,
 * and prints next steps. Designed to run once after install.
 *
 * Pure functions (formatConfig, checkPrerequisites) are exported for testing.
 * The interactive prompt loop is in promptConfig (not exported).
 */

import { createInterface } from "node:readline";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import chalk from "chalk";
import { parse as parseYaml } from "yaml";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type Provider = "codex-cli" | "openai-api" | "anthropic" | "ollama";

export interface InitConfig {
  provider: Provider;
  /** API key (OpenAI or Anthropic). Not written to config for codex-cli/ollama. */
  apiKey?: string;
  /** fast_model tier — optional. */
  fastModel?: string;
  /** smart_model tier — optional. */
  smartModel?: string;
  /** Slack incoming webhook URL — optional. */
  slackWebhook?: string;
}

export interface PrereqResult {
  ok: boolean;
  warnings: string[];
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Format an InitConfig as a .phase2s.yaml string.
 * Produces a commented file so users can easily extend it.
 */
export function formatConfig(config: InitConfig): string {
  const lines: string[] = [
    "# Phase2S configuration — generated by phase2s init",
    "# Docs: https://github.com/scanton/phase-2-s/blob/main/docs/configuration.md",
    "",
    `provider: ${config.provider}`,
  ];

  if (config.provider === "openai-api" && config.apiKey) {
    lines.push(`apiKey: "${config.apiKey}"`);
    lines.push("");
    lines.push("# Consider using OPENAI_API_KEY env var instead of storing keys in config.");
  }

  if (config.provider === "anthropic" && config.apiKey) {
    lines.push(`anthropicApiKey: "${config.apiKey}"`);
    lines.push("");
    lines.push("# Consider using ANTHROPIC_API_KEY env var instead of storing keys in config.");
  }

  const hasTiers = config.fastModel || config.smartModel;
  if (hasTiers) {
    lines.push("");
    lines.push("# Model tier routing");
    lines.push("# Skills declare 'model: fast' or 'model: smart' in their SKILL.md frontmatter.");
    if (config.fastModel) lines.push(`fast_model: ${config.fastModel}`);
    if (config.smartModel) lines.push(`smart_model: ${config.smartModel}`);
  }

  if (config.slackWebhook) {
    lines.push("");
    lines.push("# Notifications — sent after dark factory runs (phase2s goal --notify)");
    lines.push("notify:");
    lines.push(`  slack: "${config.slackWebhook}"`);
    lines.push("  # mac: true  # uncomment to enable macOS system notifications too");
  }

  return lines.join("\n") + "\n";
}

/**
 * Check that the prerequisites for the chosen provider are available.
 * Returns a list of warnings (not errors — users can fix post-init).
 * Never throws.
 */
export function checkPrerequisites(config: InitConfig): PrereqResult {
  const warnings: string[] = [];

  switch (config.provider) {
    case "codex-cli": {
      const result = spawnSync("codex", ["--version"], { stdio: "pipe" });
      if (result.error) {
        warnings.push(
          "codex CLI not found in PATH. Install with: npm install -g @openai/codex",
        );
      }
      break;
    }
    case "openai-api": {
      if (config.apiKey && !config.apiKey.startsWith("sk-")) {
        warnings.push("OpenAI API key should start with 'sk-'. Double-check your key.");
      }
      if (!config.apiKey && !process.env.OPENAI_API_KEY) {
        warnings.push(
          "No API key provided. Set OPENAI_API_KEY or re-run phase2s init.",
        );
      }
      break;
    }
    case "anthropic": {
      if (config.apiKey && !config.apiKey.startsWith("sk-ant-")) {
        warnings.push("Anthropic API key should start with 'sk-ant-'. Double-check your key.");
      }
      if (!config.apiKey && !process.env.ANTHROPIC_API_KEY) {
        warnings.push(
          "No API key provided. Set ANTHROPIC_API_KEY or re-run phase2s init.",
        );
      }
      break;
    }
    case "ollama": {
      const result = spawnSync("ollama", ["list"], { stdio: "pipe" });
      if (result.error) {
        warnings.push(
          "ollama not found in PATH. Install from https://ollama.com and start with: ollama serve",
        );
      }
      break;
    }
  }

  return { ok: warnings.length === 0, warnings };
}

/**
 * Read an existing .phase2s.yaml and extract values to pre-fill prompts.
 * Returns an empty object if the file doesn't exist or can't be parsed.
 */
export function readExistingConfig(configPath: string): Record<string, unknown> {
  try {
    const raw = readFileSync(configPath, "utf8");
    const parsed = parseYaml(raw);
    return (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed))
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

// ---------------------------------------------------------------------------
// runInit — entry point
// ---------------------------------------------------------------------------

export interface InitOptions {
  /** Skip interactive prompts. Uses provider from flags or codex-cli default. */
  nonInteractive?: boolean;
  /** Provider override for non-interactive mode. */
  provider?: string;
  /** API key override for non-interactive mode. */
  apiKey?: string;
  /** Fast model override. */
  fastModel?: string;
  /** Smart model override. */
  smartModel?: string;
  /** Slack webhook override. */
  slackWebhook?: string;
}

export async function runInit(options: InitOptions = {}): Promise<void> {
  const configPath = resolve(".phase2s.yaml");
  const existing = existsSync(configPath);

  if (existing && !options.nonInteractive) {
    console.log(chalk.yellow("  ⚠  A .phase2s.yaml already exists — values will be pre-filled from it.\n"));
  }

  let config: InitConfig;

  if (options.nonInteractive) {
    // Non-interactive: assemble config from flags, validate, write.
    const providerRaw = options.provider ?? "codex-cli";
    const validProviders: Provider[] = ["codex-cli", "openai-api", "anthropic", "ollama"];
    if (!validProviders.includes(providerRaw as Provider)) {
      throw new Error(`Unknown provider: ${providerRaw}. Valid: ${validProviders.join(", ")}`);
    }
    config = {
      provider: providerRaw as Provider,
      apiKey: options.apiKey,
      fastModel: options.fastModel,
      smartModel: options.smartModel,
      slackWebhook: options.slackWebhook,
    };
  } else {
    const existingConfig = readExistingConfig(configPath);
    config = await promptConfig(existingConfig);
  }

  // Validate prerequisites
  const { warnings } = checkPrerequisites(config);
  for (const warning of warnings) {
    console.warn(chalk.yellow(`\n  ⚠  ${warning}`));
  }

  // Write config
  const yaml = formatConfig(config);
  writeFileSync(configPath, yaml, "utf8");

  console.log(chalk.green(`\n  ✓  Written .phase2s.yaml`));
  console.log("");
  printNextSteps(config.provider);
}

// ---------------------------------------------------------------------------
// Interactive prompt loop
// ---------------------------------------------------------------------------

async function promptConfig(existing: Record<string, unknown>): Promise<InitConfig> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const ask = (q: string): Promise<string> =>
    new Promise((resolve) => rl.question(q, (a) => resolve(a.trim())));

  console.log(chalk.bold("  Phase2S setup\n"));

  // --- Provider ---
  console.log("  Provider:");
  console.log("    1  ChatGPT subscription (codex-cli) — recommended, no API key needed");
  console.log("    2  OpenAI API key");
  console.log("    3  Anthropic API key");
  console.log("    4  Local Ollama (no internet required)");
  console.log("");

  const providerToNum: Record<string, string> = {
    "codex-cli": "1", "openai-api": "2", "anthropic": "3", "ollama": "4",
  };
  const numToProvider: Record<string, Provider> = {
    "1": "codex-cli", "2": "openai-api", "3": "anthropic", "4": "ollama",
  };
  const defaultNum = providerToNum[String(existing.provider)] ?? "1";

  const providerRaw = await ask(`  Choice [${defaultNum}]: `);
  const providerKey = providerRaw || defaultNum;
  const provider: Provider = numToProvider[providerKey] ?? (Object.keys(numToProvider).includes(providerKey) ? providerKey as Provider : "codex-cli");

  const config: InitConfig = { provider };

  // --- API key (if needed) ---
  if (provider === "openai-api" || provider === "anthropic") {
    const keyField = provider === "anthropic" ? "anthropicApiKey" : "apiKey";
    const currentKey = String(existing[keyField] ?? "");
    const hint = provider === "anthropic" ? "sk-ant-..." : "sk-...";
    const prompt = currentKey
      ? `  API key (current: ${currentKey.slice(0, 10)}...) [enter to keep]: `
      : `  API key (${hint}): `;
    const key = await ask(prompt);
    config.apiKey = key || currentKey || undefined;
  }

  // --- Model tiers (optional) ---
  const existingFast = String(existing.fast_model ?? "");
  const existingSmart = String(existing.smart_model ?? "");
  if (existingFast || existingSmart) {
    config.fastModel = existingFast || undefined;
    config.smartModel = existingSmart || undefined;
    const update = await ask(`  Update model tiers (fast: ${existingFast || "unset"}, smart: ${existingSmart || "unset"})? (y/N): `);
    if (update.toLowerCase().startsWith("y")) {
      const fast = await ask(`  Fast model [${existingFast || "e.g. gpt-4o-mini"}]: `);
      const smart = await ask(`  Smart model [${existingSmart || "e.g. o3"}]: `);
      config.fastModel = fast || existingFast || undefined;
      config.smartModel = smart || existingSmart || undefined;
    }
  } else {
    const configureTiers = await ask("  Configure fast/smart model tiers for cost optimization? (y/N): ");
    if (configureTiers.toLowerCase().startsWith("y")) {
      const fast = await ask("  Fast model (e.g. gpt-4o-mini for quick tasks): ");
      const smart = await ask("  Smart model (e.g. o3 for deep analysis): ");
      config.fastModel = fast || undefined;
      config.smartModel = smart || undefined;
    }
  }

  // --- Slack webhook (optional) ---
  const existingSlack = String(
    (existing.notify as Record<string, unknown> | undefined)?.slack ?? "",
  );
  if (existingSlack) {
    const updateSlack = await ask(
      `  Slack webhook (current: ${existingSlack.slice(0, 35)}...) — update? (y/N): `,
    );
    if (updateSlack.toLowerCase().startsWith("y")) {
      const slack = await ask("  New Slack webhook URL (or 'none' to remove): ");
      config.slackWebhook = slack.toLowerCase() === "none" ? undefined : (slack || existingSlack);
    } else {
      config.slackWebhook = existingSlack;
    }
  } else {
    const slack = await ask(
      "  Slack webhook URL for notifications? (optional — press enter to skip): ",
    );
    config.slackWebhook = slack || undefined;
  }

  rl.close();
  return config;
}

// ---------------------------------------------------------------------------
// Next steps
// ---------------------------------------------------------------------------

function printNextSteps(provider: Provider): void {
  console.log("  Get started:");
  if (provider === "codex-cli") {
    console.log("    1.  Authenticate Codex CLI (one time):  codex auth");
    console.log("    2.  Start the REPL:                     phase2s");
    console.log("    3.  Or run a skill directly:            phase2s run \"/explain src/index.ts\"");
  } else if (provider === "ollama") {
    console.log("    1.  Pull a model (if not done):  ollama pull llama3.1:8b");
    console.log("    2.  Start the REPL:              phase2s");
    console.log("    3.  Or run a skill:              phase2s run \"/explain src/index.ts\"");
  } else {
    console.log("    1.  Start the REPL:              phase2s");
    console.log("    2.  Or run a skill directly:     phase2s run \"/explain src/index.ts\"");
  }
  console.log("");
  console.log(chalk.dim("  Docs: https://github.com/scanton/phase-2-s/blob/main/docs/getting-started.md"));
  console.log("");
}
